# Data/Task configuration
dataset: Accurate_Retrieval
chunk_size: 4096
debug: false
seed: 42

# specific configuration
context_max_length: 524288        
sub_dataset: ruler_niah_mq_448K 
generation_max_length: 100 
test_files: ''
demo_files: ''
use_chat_template: true
max_test_samples: 100
shots: 0
tag: null

