# Data/Task configuration
dataset: Test_Time_Learning
chunk_size: 4096
debug: false
seed: 42

# specific configuration
context_max_length: 1480000
sub_dataset: recsys_redial_full
generation_max_length: 300
test_files: ''
demo_files: ''
use_chat_template: true
max_test_samples: 1
shots: 0
tag: null

