# Data/Task configuration
dataset: Accurate_Retrieval
chunk_size: 4096
debug: false
seed: 42

# specific configuration
context_max_length: 1200000                 
sub_dataset: infbench_qa_eng_shots2      
generation_max_length: 10                 
test_files: ''
demo_files: ''
use_chat_template: true
max_test_samples: 100
shots: 2
tag: null

