agent_name: Structure_rag_memo_rag
model: gpt-4o-mini
temperature: 0.7
input_length_limit: 800000 #1000000, 500K for recsys
buffer_length: 200
output_dir: ./outputs/gpt-4o-mini-memo_rag

retrieve_num: 3