agent_name: Structure_rag_raptor
model: gpt-4o-mini
temperature: 0.7
input_length_limit: 280000   ###500k for recsys, other is 1000K
buffer_length: 200
output_dir: ./outputs/gpt-4o-mini-raptor

retrieve_num: 10