agent_name: Structure_rag_mem0
model: gpt-4o-mini
temperature: 0.7
input_length_limit: 10000000
buffer_length: 1000
output_dir: ./outputs/gpt-4o-mini-mem0

agent_chunk_size: 4096    
retrieve_num: 100
